In [1]:
import json
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import time
import os

In [3]:
thisfile="../../LargeDataset/tradewar/alltw.txt"

In [4]:
myfile=[]
for file in os.listdir("../../LargeDataset/tradewar/tw/tw"):
    myfile.append("../../LargeDataset/tradewar/tw/tw/"+file)

In [5]:
myfile

['../../LargeDataset/tradewar/tw/tw/TW.txt',
 '../../LargeDataset/tradewar/tw/tw/TW10.txt',
 '../../LargeDataset/tradewar/tw/tw/TW10_2.txt',
 '../../LargeDataset/tradewar/tw/tw/TW11_1.txt',
 '../../LargeDataset/tradewar/tw/tw/TW11__1.txt',
 '../../LargeDataset/tradewar/tw/tw/TW12.txt',
 '../../LargeDataset/tradewar/tw/tw/TW12_1.txt',
 '../../LargeDataset/tradewar/tw/tw/TW12_2.txt',
 '../../LargeDataset/tradewar/tw/tw/TW13.txt',
 '../../LargeDataset/tradewar/tw/tw/TW14.txt',
 '../../LargeDataset/tradewar/tw/tw/TW15.txt',
 '../../LargeDataset/tradewar/tw/tw/TW16.txt',
 '../../LargeDataset/tradewar/tw/tw/TW2-2.txt',
 '../../LargeDataset/tradewar/tw/tw/TW2.txt',
 '../../LargeDataset/tradewar/tw/tw/TW4.txt',
 '../../LargeDataset/tradewar/tw/tw/TW5.txt',
 '../../LargeDataset/tradewar/tw/tw/TW6.txt',
 '../../LargeDataset/tradewar/tw/tw/TW7.txt',
 '../../LargeDataset/tradewar/tw/tw/TW7_2.txt',
 '../../LargeDataset/tradewar/tw/tw/TW8.txt',
 '../../LargeDataset/tradewar/tw/tw/TW8_2.txt',
 '../../LargeDataset/tradewar/tw/tw/TW9.txt']

In [6]:
tweets_data=[]
for thisfile in myfile:
    with open(thisfile, 'r',encoding="utf-8") as f:
        for line in f:
            try:
                tweet=json.loads(line)
                tweets_data.append(tweet)
            except:
                continue

In [7]:
len(tweets_data)

32109

In [98]:
tweets_data[1]

{'contributors': None,
 'coordinates': None,
 'created_at': 'Mon Apr 02 15:01:36 +0000 2018',
 'display_text_range': [0, 140],
 'entities': {'hashtags': [],
  'symbols': [],
  'urls': [{'display_url': 'twitter.com/i/web/status/9‚Ä¶',
    'expanded_url': 'https://twitter.com/i/web/status/980822563679911937',
    'indices': [117, 140],
    'url': 'https://t.co/oGvn3bf93L'}],
  'user_mentions': []},
 'extended_tweet': {'display_text_range': [0, 154],
  'entities': {'hashtags': [],
   'symbols': [],
   'urls': [{'display_url': 'twitter.com/HaroldR01/stat‚Ä¶',
     'expanded_url': 'https://twitter.com/HaroldR01/status/980778709430034432',
     'indices': [155, 178],
     'url': 'https://t.co/o5BxeX6l6f'}],
   'user_mentions': []},
  'full_text': "Hope he's ready to give aid to the farmers.  He'll probably wait for Willy Nelson and others to hold concerts to help them.  Thanks again stable genius.üê∑üêñ https://t.co/o5BxeX6l6f"},
 'favorite_count': 0,
 'favorited': False,
 'filter_level': 'low',
 'geo': None,
 'id': 980822563679911937,
 'id_str': '980822563679911937',
 'in_reply_to_screen_name': None,
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'is_quote_status': True,
 'lang': 'en',
 'place': None,
 'possibly_sensitive': False,
 'quote_count': 0,
 'quoted_status': {'contributors': None,
  'coordinates': None,
  'created_at': 'Mon Apr 02 12:07:20 +0000 2018',
  'entities': {'hashtags': [],
   'symbols': [],
   'urls': [{'display_url': 'twitter.com/i/web/status/9‚Ä¶',
     'expanded_url': 'https://twitter.com/i/web/status/980778709430034432',
     'indices': [117, 140],
     'url': 'https://t.co/uQMXOFuMCe'}],
   'user_mentions': []},
  'extended_tweet': {'display_text_range': [0, 237],
   'entities': {'hashtags': [],
    'symbols': [],
    'urls': [],
    'user_mentions': []},
   'full_text': "China's new tariffs on pork effect states that voted for Trump:\nIowa - $4.2 b\nNorth Carolina - $1.46 b \nIndiana - $1.04 b\nOklahoma - $952.7 m\nMissouri - $791 m \nNebraska - $657.5 m\nWisconsin - $605.2 m \nOhio - $542.7 m\n(data $ US Census)"},
  'favorite_count': 8,
  'favorited': False,
  'filter_level': 'low',
  'geo': None,
  'id': 980778709430034432,
  'id_str': '980778709430034432',
  'in_reply_to_screen_name': None,
  'in_reply_to_status_id': None,
  'in_reply_to_status_id_str': None,
  'in_reply_to_user_id': None,
  'in_reply_to_user_id_str': None,
  'is_quote_status': False,
  'lang': 'en',
  'place': {'attributes': {},
   'bounding_box': {'coordinates': [[[-98.361306, 29.53047],
      [-98.361306, 29.581166],
      [-98.318549, 29.581166],
      [-98.318549, 29.53047]]],
    'type': 'Polygon'},
   'country': 'United States',
   'country_code': 'US',
   'full_name': 'Live Oak, TX',
   'id': '90ff9cc0c4682e60',
   'name': 'Live Oak',
   'place_type': 'city',
   'url': 'https://api.twitter.com/1.1/geo/id/90ff9cc0c4682e60.json'},
  'quote_count': 2,
  'reply_count': 2,
  'retweet_count': 3,
  'retweeted': False,
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'text': "China's new tariffs on pork effect states that voted for Trump:\nIowa - $4.2 b\nNorth Carolina - $1.46 b \nIndiana - $‚Ä¶ https://t.co/uQMXOFuMCe",
  'truncated': True,
  'user': {'contributors_enabled': False,
   'created_at': 'Thu Apr 19 14:56:07 +0000 2012',
   'default_profile': False,
   'default_profile_image': False,
   'description': 'University Professor (Ret.), Poet, gardener, community volunteer living  a BLUE life in a Red state.',
   'favourites_count': 22588,
   'follow_request_sent': None,
   'followers_count': 1195,
   'following': None,
   'friends_count': 2026,
   'geo_enabled': True,
   'id': 557862834,
   'id_str': '557862834',
   'is_translator': False,
   'lang': 'en',
   'listed_count': 8,
   'location': 'San Antonio, TX',
   'name': 'Harold R. PhD',
   'notifications': None,
   'profile_background_color': '000000',
   'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
   'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
   'profile_background_tile': False,
   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/557862834/1514986813',
   'profile_image_url': 'http://pbs.twimg.com/profile_images/935152760051326976/g6uAb7KC_normal.jpg',
   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/935152760051326976/g6uAb7KC_normal.jpg',
   'profile_link_color': '91D2FA',
   'profile_sidebar_border_color': '000000',
   'profile_sidebar_fill_color': '000000',
   'profile_text_color': '000000',
   'profile_use_background_image': False,
   'protected': False,
   'screen_name': 'HaroldR01',
   'statuses_count': 12552,
   'time_zone': 'Central Time (US & Canada)',
   'translator_type': 'none',
   'url': None,
   'utc_offset': -18000,
   'verified': False}},
 'quoted_status_id': 980778709430034432,
 'quoted_status_id_str': '980778709430034432',
 'reply_count': 0,
 'retweet_count': 0,
 'retweeted': False,
 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
 'text': "Hope he's ready to give aid to the farmers.  He'll probably wait for Willy Nelson and others to hold concerts to he‚Ä¶ https://t.co/oGvn3bf93L",
 'timestamp_ms': '1522681296640',
 'truncated': True,
 'user': {'contributors_enabled': False,
  'created_at': 'Mon Jun 17 15:55:23 +0000 2013',
  'default_profile': False,
  'default_profile_image': False,
  'description': "Retired. Wire wrapping jewelry instructions. Animal lover (espeially cats). Political junkie and beliver in global warming. I can spell just can't type.",
  'favourites_count': 6353,
  'follow_request_sent': None,
  'followers_count': 457,
  'following': None,
  'friends_count': 451,
  'geo_enabled': False,
  'id': 1525168716,
  'id_str': '1525168716',
  'is_translator': False,
  'lang': 'en',
  'listed_count': 1,
  'location': 'california',
  'name': 'Donna ',
  'notifications': None,
  'profile_background_color': '000000',
  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme16/bg.gif',
  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme16/bg.gif',
  'profile_background_tile': False,
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1525168716/1519230212',
  'profile_image_url': 'http://pbs.twimg.com/profile_images/912735370596384768/cureeelR_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/912735370596384768/cureeelR_normal.jpg',
  'profile_link_color': '91D2FA',
  'profile_sidebar_border_color': '000000',
  'profile_sidebar_fill_color': '000000',
  'profile_text_color': '000000',
  'profile_use_background_image': False,
  'protected': False,
  'screen_name': 'dragonjewls',
  'statuses_count': 4114,
  'time_zone': None,
  'translator_type': 'none',
  'url': None,
  'utc_offset': None,
  'verified': False}}

In [8]:
tweets=pd.DataFrame()# store the final result

In [32]:
# text: the text of the tweet itself
# created_at: the date of creation
# favorite_count, retweet_count: the number of favourites and retweets
# favorited, retweeted: boolean stating whether the authenticated user (you) have favourited or retweeted this tweet
# lang: acronym for the language (e.g. ‚Äúen‚Äù for english)
# id: the tweet identifier
# place, coordinates, geo: geo-location information if available
# user: the author‚Äôs full profile
# entities: list of entities like URLs, @-mentions, hashtags and symbols
# in_reply_to_user_id: user identifier if the tweet is a reply to a specific user
# in_reply_to_status_id: status identifier id the tweet is a reply to a specific status

In [43]:
def get_retweetid(tweet):
    try:
        return(tweet["retweeted_status"]["id"])
    except: 
        return None
    
def get_retweet_username(tweet):
    try:
        return(tweet["retweeted_status"]["user"]["name"])
    except: 
        return None
def get_retweet_followers_count(tweet):
    try:
        return(tweet["retweeted_status"]["user"]["followers_count"])
    except: 
        return None
def get_retweet_fa(tweet):
    try:
        return(tweet["retweeted_status"]["favorite_count"])
    except: 
        return None
def get_retweet_retw(tweet):
    try:
        return(tweet["retweeted_status"]["retweet_count"])
    except: 
        return None
def get_retweet_rep(tweet):
    try:
        return(tweet["retweeted_status"]["reply_count"])
    except: 
        return None

In [19]:
tweets=pd.DataFrame()
tweets['id'] = list(map(lambda tweet: tweet['id'], tweets_data))
tweets['country']=list(map(lambda tweet: tweet['place']['country'] if tweet['place']!= None else None, tweets_data))
tweets['text']=list(map(lambda tweet: tweet['text'], tweets_data))
tweets["user_id"]=list(map(lambda tweet:tweet["user"]["id"],tweets_data))
tweets["user_name"]=list(map(lambda tweet:tweet["user"]["name"],tweets_data))
tweets["user_followers"]=list(map(lambda tweet:tweet["user"]["followers_count"],tweets_data))
tweets['user_loc']=list(map(lambda tweet: tweet['user']['location'], tweets_data))
tweets['lang']=list(map(lambda tweet: tweet['lang'], tweets_data))
# tweets['retweeted'] = list(map(lambda tweet: tweet['retweeted'], tweets_data))
tweets['retweet_id']=list(map(get_retweetid, tweets_data))
tweets['retweet_status_user_name']=list(map(get_retweet_username, tweets_data))
tweets['retweet_status_follower_count']=list(map(get_retweet_followers_count, tweets_data))


tweets['retweet_status_favorite_count']=list(map(get_retweetid, tweets_data))
tweets['retweet_status_retweet_count']=list(map(get_retweet_retw, tweets_data))
tweets['retweet_status_reply_count']=list(map(get_retweet_rep, tweets_data))

tweets['created_at']=list(map(lambda tweet: time.strftime('%Y-%m-%d %H:%M:%S', time.strptime(tweet['created_at'],'%a %b %d %H:%M:%S +0000 %Y')), tweets_data))


# tweets['retweet_count']=list(map(lambda tweet: tweet['retweet_count'] if tweet['retweet_count']!= None else None, tweets_data))
# tweets['reply_count']=list(map(lambda tweet: tweet['reply_count'] if tweet['reply_count']!= None else None, tweets_data))
# tweets['favorite_count']=list(map(lambda tweet: tweet['favorite_count'], tweets_data))

In [44]:
tweets.head(10)

,id,country,text,user_id,user_name,user_followers,user_loc,lang,retweet_id,retweet_status_user_name,retweet_status_follower_count,retweet_status_favorite_count,retweet_status_retweet_count,retweet_status_reply_count,created_at
0,980822559901016070,None,Here‚Äôs the full list of American goods affecte...,26558316,blackwhalegroup,335,"NYC, SD, KC",en,NaN,None,NaN,NaN,NaN,NaN,2018-04-02 15:01:35
1,980822563679911937,None,Hope he's ready to give aid to the farmers. H...,1525168716,Donna,457,california,en,NaN,None,NaN,NaN,NaN,NaN,2018-04-02 15:01:36
2,980822565378838531,None,RT @RedTRaccoon: NC will pay high price for me...,1148610157,American AntiFed,16431,New Mexico,en,9.808189e+17,Red T Raccoon,97822.0,9.808189e+17,30.0,5.0,2018-04-02 15:01:37
3,980822567316590593,None,RT @MelissaLeeCNBC: Tariff impact on data alre...,601305639,Don Juan de Morocco,196,Internet,en,9.808139e+17,Melissa Lee,87491.0,9.808139e+17,3.0,1.0,2018-04-02 15:01:37
4,980822568281235456,None,The full list of 128 US products targeted by C...,2279225400,Gloria (Dem) üåäüá∫üá∏üåä,14158,"New York, USA",en,NaN,None,NaN,NaN,NaN,NaN,2018-04-02 15:01:37
5,980822568386093056,None,RT @haydenblack: Trump: I wrote the Art of the...,3440489113,Donald J. Trump,906,None,en,9.808199e+17,Hayden Black,14869.0,9.808199e+17,3.0,0.0,2018-04-02 15:01:37
6,980822571435339776,None,RT @RWPUSA: Trump's reckless trade war is pois...,782363971265425409,James Murray,471,"Tennessee, USA",en,9.807700e+17,Richard W. Painter,427703.0,9.807700e+17,1296.0,92.0,2018-04-02 15:01:38
7,980822572915941376,None,China announces retaliatory tariffs on about 1...,3971882499,Buckland,201,None,en,NaN,None,NaN,NaN,NaN,NaN,2018-04-02 15:01:38
8,980822573255557120,None,Accuracy in America with Don Irvine. Trump rul...,14132503,DonIrvine,10448,Washington DC,en,NaN,None,NaN,NaN,NaN,NaN,2018-04-02 15:01:38
9,980822575067561986,None,"RT @EdKrassen: Thanks to Trump, all U.S. Compa...",872049236560556035,Sharon Thompson,3399,"My Town, Kentucky",en,9.807803e+17,Ed Krassenstein üíé,693096.0,9.807803e+17,1156.0,177.0,2018-04-02 15:01:39

In [46]:
tweets.user_followers.describe()

count    3.210900e+04
mean     1.541823e+04
std      3.249083e+05
min      0.000000e+00
25%      1.440000e+02
50%      5.830000e+02
75%      2.213000e+03
max      2.315289e+07
Name: user_followers, dtype: float64

In [48]:
tweets.retweet_status_follower_count.describe()

count    2.226000e+04
mean     3.937319e+06
std      1.239582e+07
min      0.000000e+00
25%      2.054675e+04
50%      1.430620e+05
75%      4.569298e+05
max      5.089109e+07
Name: retweet_status_follower_count, dtype: float64

# network graph for retweet relationship

In [36]:
notnaindex=tweets["retweet_status_user_name"].notna()

In [39]:
retweet_relation=tweets.loc[notnaindex,["user_name","user_followers","retweet_status_user_name","retweet_status_follower_count"]]

In [42]:
retweet_relation.to_csv("../output/retweet_relation.csv",encoding="utf-8")

# tokenization and stop words

In [89]:
from nltk.tokenize import word_tokenize

In [90]:
import re
 
emoticons_str = r"""
    (?:
        [:=;] # Eyes
        [oO\-]? # Nose (optional)
        [D\)\]\(\]/\\OpP] # Mouth
    )"""
 
regex_str = [
    emoticons_str,
    r'<[^>]+>', # HTML tags
    r'(?:@[\w_]+)', # @-mentions
    r"(?:\#+[\w_]+[\w\'_\-]*[\w_]+)", # hash-tags
    r'http[s]?://(?:[a-z]|[0-9]|[$-_@.&amp;+]|[!*\(\),]|(?:%[0-9a-f][0-9a-f]))+', # URLs
 
    r'(?:(?:\d+,?)+(?:\.?\d+)?)', # numbers
    r"(?:[a-z][a-z'\-_]+[a-z])", # words with - and '
    r'(?:[\w_]+)', # other words
    r'(?:\S)' # anything else
]
    
tokens_re = re.compile(r'('+'|'.join(regex_str)+')', re.VERBOSE | re.IGNORECASE)
emoticon_re = re.compile(r'^'+emoticons_str+'$', re.VERBOSE | re.IGNORECASE)
 
def tokenize(s):
    return tokens_re.findall(s)
 
def preprocess(s, lowercase=False):
    tokens = tokenize(s)
    if lowercase:
        tokens =  [token if emoticon_re.search(token)  else token.lower() for token in tokens]
    return tokens
 
tweet = 'RT @marcobonzanini: just an example! :D http://example.com #NLP'
print(preprocess(tweet))
# ['RT', '@marcobonzanini', ':', 'just', 'a n', 'example', '!', ':D', 'http://example.com', '#NLP']

['RT', '@marcobonzanini', ':', 'just', 'an', 'example', '!', ':D', 'http://example.com', '#NLP']

In [91]:
from nltk.corpus import stopwords
import string
def remove_stop_words(tweet):
    punctuation = list(string.punctuation)
    stop = stopwords.words('english') + punctuation + ['rt', 'via','RT']
    terms_stop = [term for term in preprocess(tweet['text']) if term not in stop]
    return(" ".join(terms_stop))

In [92]:
tweets['clean_text']=list(map(lambda tweet: remove_stop_words(tweet), tweets_data))

DataFrame.to_csv(path_or_buf=None, sep=', ', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression=None, quoting=None, quotechar='"', line_terminator='\n', chunksize=None, tupleize_cols=None, date_format=None, doublequote=True, escapechar=None, decimal='.')[source]¬∂

In [93]:
import pandas as pd

In [94]:
tweets.to_csv("../output/clean_data_4_18_14_40.csv",encoding="utf-8")

pandas.read_csv(filepath_or_buffer, sep=', ', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, skip_footer=0, doublequote=True, delim_whitespace=False, as_recarray=None, compact_ints=None, use_unsigned=None, low_memory=True, buffer_lines=None, memory_map=False, float_precision=None)[source]

In [95]:
saved_tweets=pd.read_csv("../output/clean_data_4_18_14_40.csv",sep=",",encoding="utf-8",engine="python")

In [96]:
saved_tweets.head()

,Unnamed: 0,id,country,text,user_id,user_followers,user_loc,lang,retweet_id,retweet_status_favorite_count,retweet_status_retweet_count,retweet_status_reply_count,created_at,clean_text
0,0,9.808226e+17,NaN,Here‚Äôs the full list of American goods affecte...,26558316,335.0,"NYC, SD, KC",en,NaN,NaN,NaN,NaN,2018-04-02 15:01:35,Here ‚Äô full list American goods affected China...
1,1,9.808226e+17,NaN,Hope he's ready to give aid to the farmers. H...,1525168716,457.0,california,en,NaN,NaN,NaN,NaN,2018-04-02 15:01:36,Hope he's ready give aid farmers He'll probabl...
2,2,9.808226e+17,NaN,RT @RedTRaccoon: NC will pay high price for me...,1148610157,16431.0,New Mexico,en,9.808189e+17,9.808188756999414e+17,30.0,5.0,2018-04-02 15:01:37,@RedTRaccoon NC pay high price metals tariffs ...
3,3,9.808226e+17,NaN,RT @MelissaLeeCNBC: Tariff impact on data alre...,601305639,196.0,Internet,en,9.808139e+17,9.808139294788035e+17,3.0,1.0,2018-04-02 15:01:37,@MelissaLeeCNBC Tariff impact data already THE...
4,4,9.808226e+17,NaN,The full list of 128 US products targeted by C...,2279225400,14158.0,"New York, USA",en,NaN,NaN,NaN,NaN,2018-04-02 15:01:37,The full list 128 US products targeted China ‚Äô...

NameError: name 're' is not defined